export const BACKEND_URL =
  process.env.BACKEND_URL ?? 'ws://192.168.1.1:8000/ws/segment';

export const CAMERA_CONFIG = {
  TARGET_FRAME_WIDTH: 640,
  JPEG_QUALITY: 0.5,
  MAX_FPS: 15,
};

export const WEBSOCKET_CONFIG = {
  RECONNECT_INTERVAL_MS: 2000,
  MAX_RECONNECT_ATTEMPTS: 10,
  HEARTBEAT_INTERVAL_MS: 15000,
  FRAME_DEBOUNCE_MS: 66,
};

export const UI_CONFIG = {
  HUD_HEIGHT: 60,
  ACTION_BUTTON_WIDTH: 110,
  ACTION_BUTTON_HEIGHT: 54,
};
